##### Lab Exercise 7
##### 2347242

Q1. Create two 3×3 matrices using the random function in Numpy and perform the following operations.
    a. Product (prod)
    b. Multiplication (multiply)
    c. Dot Product (dot)

In [31]:
import numpy as np

# Create two random 3x3 matrices
matrix1 = np.random.randint(30, size=(3, 3))
matrix2 = np.random.randint(30, size=(3, 3))

# Perform matrix operations

# Product (element-wise multiplication)
product_result = np.prod([matrix1, matrix2], axis=0)

# Multiplication
multiplication_result = np.multiply(matrix1, matrix2)

# Dot Product
dot_product_result = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nProduct of the MATRIX(element-wise multiplication):")
print(product_result)
print("\nMultiplication of the MAtrix:")
print(multiplication_result)
print("\nDot Product Of two Matrix:")
print(dot_product_result)


#ignore 


Matrix 1:
[[19 10  3]
 [10 26  1]
 [18  5  0]]

Matrix 2:
[[22  1  2]
 [ 0 11 18]
 [19 22  9]]

Product of the MATRIX(element-wise multiplication):
[[418  10   6]
 [  0 286  18]
 [342 110   0]]

Multiplication of the MAtrix:
[[418  10   6]
 [  0 286  18]
 [342 110   0]]

Dot Product Of two Matrix:
[[475 195 245]
 [239 318 497]
 [396  73 126]]


Q2. Perform the following set operations using the Numpy functions.
è Union
è Intersection
è Set difference
è XOR


In [21]:
import numpy as np
n1=np.random.randint(1,100,5)
n2=np.random.randint(1,100,5)
print("matrix1:\n",n1)
print("matrix2:\n",n2)
print("Union:\n",np.union1d(n1,n2))
print("Intersection:\n",np.intersect1d(n1,n2))
print("Set difference:\n",np.setdiff1d(n1,n2))
print("XOR(Exclusive OR):\n",np.setxor1d(n1,n2))

matrix1:
 [68 79 97  8 55]
matrix2:
 [17 89 73 96 76]
Union:
 [ 8 17 55 68 73 76 79 89 96 97]
Intersection:
 []
Set difference:
 [ 8 55 68 79 97]
XOR(Exclusive OR):
 [ 8 17 55 68 73 76 79 89 96 97]


Q3. Create a 1D array using Random function and perform the following operations.
  a. Cumulative sum
  b. Cumulative Product
  c. Discrete difference (with n=3)
  d. Find the unique elements from the array

In [24]:
import numpy as np
array=np.random.randint(1,10,5)
print("array:\n",array)
print("\ncumulative sum:\n",np.cumsum(array))
print("\ncumulative product:\n",np.cumprod(array))
print("\ndiscrete difference:\n",np.diff(array, 3))
print("\nUnique Elements in the array: ",np.unique(array))


array:
 [2 5 5 1 8]

cumulative sum:
 [ 2  7 12 13 21]

cumulative product:
 [  2  10  50  50 400]

discrete difference:
 [-1 15]

Unique Elements in the array:  [1 2 5 8]


##### Q4. Create two 1D array and perform the Addition using zip(), add() and user defined function (frompyfunc())


In [25]:
import numpy as np
array1=np.array([1,2,3,4,5])
array2=np.array([3,4,5,6,7])

# Perform addition using zip() and list comprehension
zip_addition = np.array([x + y for x, y in zip(array1, array2)])

# Perform addition using numpy.add()
numpy_addition = np.add(array1, array2)

# Create a user-defined function for addition
def add(x, y):
    return x + y

# Create a ufunc from the user-defined function
ufunc_add = np.frompyfunc(add, 2, 1)

# Perform addition using the ufunc
ufunc_addition = ufunc_add(array1, array2)

# Print the arrays and the results of the addition
print("Array 1:", array1)
print("\nArray 2:", array2)
print("\nAddition using zip() and list comprehension:", zip_addition)
print("\nAddition using numpy.add():", numpy_addition)
print("\nAddition using ufunc:", ufunc_addition)

Array 1: [1 2 3 4 5]

Array 2: [3 4 5 6 7]

Addition using zip() and list comprehension: [ 4  6  8 10 12]

Addition using numpy.add(): [ 4  6  8 10 12]

Addition using ufunc: [4 6 8 10 12]


##### Q5. Find the LCM (Least Common Multiple) and GCD (Greatest Common Divisor) of an array of elements using reduce().


In [32]:
import numpy as np
from functools import reduce

# Create an array of elements
array = np.array([12, 18, 24, 36, 48])

# Find the LCM using NumPy's lcm.reduce() function
lcm_result = np.lcm.reduce(array)

# Find the GCD using NumPy's gcd.reduce() function
gcd_result = np.gcd.reduce(array)

print("Array:", array)
print("LCM:", lcm_result)
print("GCD:", gcd_result)



Array: [12 18 24 36 48]
LCM: 144
GCD: 6
