### Python  Regular Lab Exercise 9

##### Q1. Write a program to distinguish between Array Indexing and Fancy Indexing.

In [5]:
import numpy as np

# Array Indexing
a = np.array([1, 2, 3, 4, 5])
print(a[2])

# Fancy Indexing
b = np.array([1, 2, 3, 4, 5])
print(b[[1, 3]])


3
[2 4]


##### Q2. Execute the 2D array Slicing.

In [11]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slicing a 2D array
print("Original array:")
print(arr)

# Slicing rows
print("Sliced rows:")
print(arr[1:3, :])

# Slicing columns
print("Sliced columns:")
print(arr[:, 1:3])

# Slicing both rows and columns
print("Sliced rows and columns:")
print(arr[1:3, 1:3])

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sliced rows:
[[4 5 6]
 [7 8 9]]
Sliced columns:
[[2 3]
 [5 6]
 [8 9]]
Sliced rows and columns:
[[5 6]
 [8 9]]


##### Q3. Create the 5-Dimensional arrays using ‘ndmin’.

In [6]:
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print("5-dimensional array:")
print(arr)
print("Shape of array:", arr.shape)
print(arr.ndim)

5-dimensional array:
[[[[[1 2 3 4]]]]]
Shape of array: (1, 1, 1, 1, 4)
5


##### Q4.Reshape the array from 1-D to 2-D array.

In [9]:
import numpy as np

# Create a 1-D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Reshape the array to a 2-D array with 2 rows and 4 columns
newarr = arr.reshape(2, 4)

# Print the original and reshaped arrays
print("Original array:")
print(arr)
print("\nReshaped array:")
print(newarr)

Original array:
[1 2 3 4 5 6 7 8]

Reshaped array:
[[1 2 3 4]
 [5 6 7 8]]


##### Q5. Perform the Stack functions in Numpy arrays – Stack(), hstack(), vstack(), and dstack().

In [8]:
import numpy as np

# Create two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Stack the arrays vertically using vstack()
vstacked = np.vstack((arr1, arr2))

# Stack the arrays horizontally using hstack()
hstacked = np.hstack((arr1, arr2))

# Stack the arrays depth-wise using dstack()
dstacked = np.dstack((arr1, arr2))

# Stack the arrays along a new axis using stack()
stacked = np.stack((arr1, arr2), axis=1)

# Print the stacked arrays
print("Vertically stacked array:")
print(vstacked)

print("\nHorizontally stacked array:")
print(hstacked)

print("\nDepth-wise stacked array:")
print(dstacked)

print("\nStacked array along a new axis:")
print(stacked)

Vertically stacked array:
[[1 2 3]
 [4 5 6]]

Horizontally stacked array:
[1 2 3 4 5 6]

Depth-wise stacked array:
[[[1 4]
  [2 5]
  [3 6]]]

Stacked array along a new axis:
[[1 4]
 [2 5]
 [3 6]]


##### Q6. Perform the searchsort method in Numpy array.

In [7]:
import numpy as np

# Create an array
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])

# Sort the array using np.sort()
sorted_arr = np.sort(arr)

# Find the indices that would sort the array using np.argsort()
sort_indices = np.argsort(arr)

# Search for an element in the array using np.searchsorted()
search_index = np.searchsorted(sorted_arr, 5)

# Print the original and sorted arrays, sort indices, and search index
print("Original array:")
print(arr)

print("\nSorted array:")
print(sorted_arr)

print("\nSort indices:")
print(sort_indices)

print("\nSearch index:")
print(search_index)

Original array:
[3 1 4 1 5 9 2 6 5 3 5]

Sorted array:
[1 1 2 3 3 4 5 5 5 6 9]

Sort indices:
[ 1  3  6  0  9  2  4  8 10  7  5]

Search index:
6


##### Q7. Create Numpy Structured array using your domain features.

In [6]:
import numpy as np

# Define the data type for the structured array
dt = np.dtype([('account_number', 'i4'), ('account_holder', 'S20'), ('balance', 'f8')])

# Create the structured array
arr = np.array([(1001, 'Alice', 5000.0), (1002, 'Bob', 10000.0), (1003, 'Charlie', 7500.0)], dtype=dt)

# Print the structured array
print(arr)

[(1001, b'Alice',  5000.) (1002, b'Bob', 10000.)
 (1003, b'Charlie',  7500.)]


##### Q8. Create Data frame using List and Dictionary.

In [5]:
import pandas as pd

# Create a DataFrame using a list of dictionaries
data = [{'name': 'Alice', 'age': 25}, {'name': 'Bob', 'age': 30}, {'name': 'Charlie', 'age': 35}]
df1 = pd.DataFrame(data)

# Create a DataFrame using a dictionary of lists
data = {'name': ['Alice', 'Bob', 'Charlie'], 'age': [25, 30, 35]}
df2 = pd.DataFrame(data)

# Print the DataFrames
print("DataFrame using a list of dictionaries:")
print(df1)

print("\nDataFrame using a dictionary of lists:")
print(df2)

DataFrame using a list of dictionaries:
      name  age
0    Alice   25
1      Bob   30
2  Charlie   35

DataFrame using a dictionary of lists:
      name  age
0    Alice   25
1      Bob   30
2  Charlie   35


##### Q9. Create Data frame on your Domain area and perform the following operations to find and eliminate the missing data from the dataset.
• isnull()
• notnull()
• dropna()
• fillna()
• replace()
• interpolate()

In [3]:
import pandas as pd
import numpy as np

# Create a dictionary of lists for the DataFrame
data = {'account_number': [1001, 1002, 1003, 1004, 1005],
        'account_holder': ['Alice', 'Bob', 'Charlie', 'David', 'Emily'],
        'balance': [5000.0, 10000.0, np.nan, 7500.0, np.nan]}

# Create the DataFrame
df = pd.DataFrame(data)

# Find missing data using isnull()
print("Missing data:")
print(df.isnull())

# Find non-missing data using notnull()
print("\nNon-missing data:")
print(df.notnull())

# Drop missing data using dropna()
df_dropped = df.dropna()
print("\nDataFrame with missing data dropped:")
print(df_dropped)

# Fill missing data using fillna()
df_filled = df.fillna(0)
print("\nDataFrame with missing data filled:")
print(df_filled)

# Replace missing data using replace()
df_replaced = df.replace(np.nan, 0)
print("\nDataFrame with missing data replaced:")
print(df_replaced)

# Interpolate missing data using interpolate()
df_interpolated = df.interpolate()
print("\nDataFrame with missing data interpolated:")
print(df_interpolated)

Missing data:
   account_number  account_holder  balance
0           False           False    False
1           False           False    False
2           False           False     True
3           False           False    False
4           False           False     True

Non-missing data:
   account_number  account_holder  balance
0            True            True     True
1            True            True     True
2            True            True    False
3            True            True     True
4            True            True    False

DataFrame with missing data dropped:
   account_number account_holder  balance
0            1001          Alice   5000.0
1            1002            Bob  10000.0
3            1004          David   7500.0

DataFrame with missing data filled:
   account_number account_holder  balance
0            1001          Alice   5000.0
1            1002            Bob  10000.0
2            1003        Charlie      0.0
3            1004          David   7500.

##### Q10. Perform the Hierarchical Indexing in the above created dataset.

In [4]:
import pandas as pd

# Create a dictionary of lists for the DataFrame
data = {'account_number': [1001, 1002, 1003, 1004, 1005],
        'account_holder': ['Alice', 'Bob', 'Charlie', 'David', 'Emily'],
        'balance': [5000.0, 10000.0, 7500.0, 6000.0, 9000.0],
        'branch': ['A', 'B', 'A', 'C', 'B']}

# Create the DataFrame
df = pd.DataFrame(data)

# Set the hierarchical index
df.set_index(['branch', 'account_holder'], inplace=True)

# Print the DataFrame with hierarchical index
print(df)

                       account_number  balance
branch account_holder                         
A      Alice                     1001   5000.0
B      Bob                       1002  10000.0
A      Charlie                   1003   7500.0
C      David                     1004   6000.0
B      Emily                     1005   9000.0
